# -*- coding: utf-8 -*-

NFSAAS_USERNAME = 'ricardo.dias'
NFSAAS_PASSWORD = 'RickGlobo12@'
NFSAAS_URL = 'http://nfsaas.globoi.com/api/'

NFSAAS_TEAMID = 4
NFSAAS_PROJECTID = 5

## SERA MIGRADO PARA TABELA
NFSAAS_ENVIRONMENTID = 1
NFSAAS_SIZEID = 1
